config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'apartments#index'
  get "apartments/new", to: "apartments#new"
  get "apartments/:id", to: "apartments#show", as: :apartment
  post "apartments", to: "apartments#create"
  get "apartments/:id/edit", to: "apartments#edit", as: :edit_apartment
  patch "apartments/:id", to: "apartments#update"
  delete "apartments/:id", to: "apartments#destroy"
  patch "bookings/:id/confirm", to: "bookings#confirm", as: :confirm_booking
  patch "bookings/:id/decline", to: "bookings#decline", as: :decline_booking
  patch "apartments/:id/activate", to: "apartments#activate", as: :activate_apartment
  patch "apartments/:id/deactivate", to: "apartments#deactivate", as: :deactivate_apartment
  resources :bookings, only: [ :create, :index, :show] do
    resources :payments, only: :new
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :apartment
  monetize :amount_cents
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def index
      @active_apartments = Apartment.where(user_id: current_user.id, status: "active")
      @inactive_apartments = Apartment.where(user_id: current_user.id, status: "inactive")
      @pending_bookings = Booking.where(user_id: current_user.id, status: "pending")
      @accepted_bookings = Booking.where(user_id: current_user.id, status: "accepted")
      @declined_bookings = Booking.where(user_id: current_user.id, status: "declined")
    end
    def create
        apartment = Apartment.find(params[:apartment_id])
        description = params[:description]
        booking  = Booking.create!(apartment: apartment, state: 'pending', user: current_user, description: description)
      
        session = Stripe::Checkout::Session.create(
          payment_method_types: ['card'],
          line_items: [{
            name: apartment.id,
            images: [apartment.photos[0]],
            amount: apartment.rent_cents,
            currency: 'eur',
            quantity: 1
          }],
          success_url: booking_url(booking),
          cancel_url: booking_url(booking)
        )
      
        booking.update(checkout_session_id: session.id)
        redirect_to bookings_path
        # redirect_to new_booking_payment_path(booking)
    end

    def confirm
      @booking = Booking.find(params[:id])
      @booking.status = "confirmed"
      @booking.apartment.status = "inactive"
      @booking.apartment.save
      @booking.save
      redirect_to bookings_path
    end

    def decline
      @booking = Booking.find(params[:id])
      @booking.status = "declined"
      @booking.save
      redirect_to bookings_path
    end

end

app/views/bookings/index.html.erb
<!-- ======= Aktiivsed kuulutused sektsioon ======= -->
<div class="container my-5">
    <h2>Minu kuulutused</h2>
</div>

<div class="container my-5">
    <% @active_apartments.each do |apartment| %>
        <div class="card mb-3">
            <div class="row g-0">
                
                <div class="col-md-3 my-3" style="display: flex; justify-content: center;">
                            <%= cl_image_tag apartment.photos[0].key, crop: :fit, width: 180, height: 300, class:"ml-3" %>
                        </div>
                <div class="col-md-9">
                    <div class="card-body">
                        <h5 class="card-title"><%= apartment.description %></h5>
                        <button type="button" class="btn my-3 btn-aktiivne">Kuulutus on aktiivne</button>
                        <%= link_to "Arhiveeri kuulutus", deactivate_apartment_path(apartment), method: :patch, class: "btn my-3 btn-secondary" %>
                        <%= link_to "Muuda kuulutuse infot", edit_apartment_path(apartment), class: "btn  my-3 btn-primary" %>
                        <%= link_to "Kustuta kuulutus",
                            apartment_path(apartment),
                            method: :delete,
                            data: { confirm: "Olete kindel, et soovite kustutada kuulutuse?" },
                            class: "btn my-3 btn-eemalda" %>
                    </div>
                </div>
            </div>
        </div>  
    <% end %>   
</div>

<!-- ======= Mitteaktiivsed kuulutused sektsioon ======= -->
<div class="container my-5">
    <% @inactive_apartments.each do |apartment| %>
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-3 my-3" style="display: flex; justify-content: center;">
                            <%= cl_image_tag apartment.photos[0].key, crop: :fit, width: 180, height: 300, class:"ml-3" %>
                        </div>
                <div class="col-md-9">
                    <div class="card-body">
                        <h5 class="card-title"><%= apartment.description %></h5>
                        <button type="button" class=" btn my-3 btn-secondary">Kuulutus on mitteaktiivne</button>
                        <%= link_to "Aktiveeri kuulutus", activate_apartment_path(apartment), method: :patch, class: "my-3 btn btn-aktiivne" %>
                        <%= link_to "Muuda kuulutuse infot", edit_apartment_path(apartment), class: "btn my-3 btn-primary" %>
                        <%= link_to "Kustuta kuulutus",
                            apartment_path(apartment),
                            method: :delete,
                            data: { confirm: "Olete kindel, et soovite kustutada kuulutuse?" },
                            class: "btn my-3 btn-eemalda" %>
                    </div>
                </div>
            </div>
        </div>  
    <% end %>   
</div>

<hr/>
<!-- ======= Kinnitust ootavad reserveeringud sektsioon ======= -->
<div class="container my-5">
    <h2>Huviliste teated</h2>
</div>

<!--- Pending apartments ---!>
<div class="container my-5">
    <% @active_apartments.each do |apartment| %>
        <% apartment.bookings.each do |booking| %>
            <% if booking.status == "pending" %>
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-3 my-3" style="display: flex; justify-content: center;">
                            <%= cl_image_tag booking.apartment.photos[0].key, crop: :fit, width: 180, height: 300, class:"ml-3" %>
                        </div>
                        <div class="col-md-9">
                            <div class="card-body">
                                <h5 class="card-title"><%= booking.apartment.description %></h5>
                                <button type="button" class="btn my-3 btn-secondary">Huviline on kirjutanud</button>
                                <p class="card-text"><%= booking.description %></p>
                                <!-- =======  link_to "Kinnita reserveering", confirm_booking_path(booking), method: :patch, class: "btn my-3 btn-primary" %>
                                 <%= link_to "Tühista reserveering ja kustuta", decline_booking_path(booking), class: "btn my-3 btn-primary" %> ======= -->
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>  
    <% end %>   
</div>
<!-- ======= Kinnitust ootavad reserveeringud sektsioon ======= -->


<!-- ======= Reserveeringud sektsioon ======= -->
<% if @accepted_bookings.any? or @pending_bookings.any? %>
    <hr/>
    <div class="container my-5">
        <h2>Sinu saadetud sõnumid</h2>
    </div>
<% end %>

<div class="container my-5">
    <% @accepted_bookings.each do |booking| %>
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-3 my-3" style="display: flex; justify-content: center;">
                            <%= cl_image_tag booking.apartment.photos[0].key, crop: :fit, width: 180, height: 300, class:"ml-3" %>
                        </div>
                <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title"><%= booking.apartment.description %></h5>
                    <p class="card-text"><%= booking.description %></p>
                    <button type="button" class="btn my-3 btn-">Reserveering on kinnitatud</button>
                </div>
                </div>
            </div>
        </div>  
    <% end %>   
</div>

<div class="container my-5">
    <% @pending_bookings.each do |booking| %>
        <div class="card mb-3">
            <div class="row g-0">
                
                <div class="col-md-3 my-3" style="display: flex; justify-content: center;">
                            <%= cl_image_tag booking.apartment.photos[0].key, crop: :fit, width: 180, height: 300, class:"ml-3" %>
                        </div>
                <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title"><%= booking.apartment.description %></h5>
                    <p class="card-text"><%= booking.description %></p>
                    <button type="button" class="btn my-3 btn-secondary">Üürileandja on sinu sõnumi kätte saanud</button>
                </div>
                </div>
            </div>
        </div>  
    <% end %>   
</div>
<!-- ======= Reserveeringud sektsioon ======= -->

app/views/bookings/show.html.erb
<div class="container my-5">
    <h3 class="my-5">Kuulutuse ülespanija on teavitatud ja kinnitab broneeringu</h3>
    <p>Broneeringuid saad näha profiili alt – Kuulutused ja reserveeringud</p>
</div>