config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'apartments#index'
  get "apartments/new", to: "apartments#new"
  get "apartments/:id", to: "apartments#show", as: :apartment
  post "apartments", to: "apartments#create"
  get "apartments/:id/edit", to: "apartments#edit", as: :edit_apartment
  patch "apartments/:id", to: "apartments#update"
  delete "apartments/:id", to: "apartments#destroy"
  patch "bookings/:id/confirm", to: "bookings#confirm", as: :confirm_booking
  patch "bookings/:id/decline", to: "bookings#decline", as: :decline_booking
  patch "apartments/:id/activate", to: "apartments#activate", as: :activate_apartment
  patch "apartments/:id/deactivate", to: "apartments#deactivate", as: :deactivate_apartment
  resources :bookings, only: [ :create, :index, :show] do
    resources :payments, only: :new
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-main">
 

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Avaleht", "/", class: "nav-link" %>
        </li>
        <li class="nav-item mr-1">
          <%= link_to "Lisa korteri kuulutus", apartments_new_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-1">
          <%= link_to "Kuulutused ja sõnumid", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-1">
          <%= link_to "Muuda profiili", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to "Logi välja", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
 
        <!----- <li class="nav-item dropdown mr-5">
           <%= cl_image_tag "user_icon_profile", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Kuulutused ja reserveeringud", bookings_path, class: "dropdown-item" %>
            <%= link_to "Muuda profiili", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Logi välja", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
          
        </li>
        -----!>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Avaleht", "/", class: "nav-link" %>
        </li>
        <li class="nav-item mr-1">
            <%= link_to "Lisa korteri kuulutus", apartments_new_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to "Logi sisse", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>